CREATE DATABASE wdiktsf;
CREATE USER wdiktsfuser WITH PASSWORD 'wdiktsf';
GRANT ALL PRIVILEGES ON DATABASE wdiktsf TO wdiktsfuser;

ALTER TABLE wdiktsf
    ADD COLUMN IF NOT EXISTS Album VARCHAR(100),
    ADD COLUMN IF NOT EXISTS Movie VARCHAR(100),
    ADD COLUMN IF NOT EXISTS TVshow VARCHAR(100);