# Generated by Django 5.0.3 on 2024-03-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdiktsf', '0002_artist_alter_song_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
    ]
