# Generated by Django 5.0.3 on 2024-03-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdiktsf', '0004_remove_song_albums_alter_song_artist_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
