# Generated by Django 5.0.3 on 2024-03-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdiktsf', '0005_alter_album_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(help_text='Select an artist(s) for this album', related_name='albums', to='wdiktsf.artist'),
        ),
    ]
